### ISSUE TITLE
Generic Micro Python Source Code

### ISSUE THREAD

**Issue by SUBBU3881** [micropython/micropython-infineon#2]
Hello,
        I am working on Infineon's Tri-Core controller and I am using AUTOSAR as OS for my automotive project. Now, I need for **generic micropython source code** for porting onto tricore controller. Please provide generic micropython source code.

Please respond as soon as possible.

Thanks and regards,
Siva Prakash Reddy

**Comment by webmeister** [comment]
The MicroPython source code is already written in a generic way, that allows it to run on many different platforms. You'll find a lot of shared code for example in the py directory, that contains the implementation of the MicroPython interpreter. Of course, some parts of the code are specific to a certain controller/architecture and those are contained in the ports directory.

**Comment by SUBBU3881** [comment]
Thanks for response. As per my project, MicroPython not needed for booting the board because already AUTOSAR is running on my board. I just want to add cross-compiled Micropython Interpreter onto flash memory. I gone through the source files in "/minimal" directory in micropython source code, and it is having STM controller's UART and GPIO details also, are they necessary for generic Micropython Interpreter.? So can you please help me in this regard.

Thanks and Regards,
Siva Prakash Reddy
