### ISSUE TITLE
Micropython Building Using Eclipse IDE

### ISSUE THREAD

**Issue by SUBBU3881** [micropython/micropython-infineon#3]
Dear Support Team,
        I am trying to build Micropython Source code for Infineon Tricore Architecture Controller with HighTec IDE (Provided by infineon) which is eclipse version and I am using Windows 10 OS. I modified main.c in /minimal directory and added to my project and tried to build it. I am facing following issue while running python script file available in /py directory

C:\Users\sivaprakashreddy\Desktop\micropython-1.9.2\py>
C:\Users\sivaprakashreddy\Desktop\micropython-1.9.2\py>makeqstrdata.py qstrdefs.h
Traceback (most recent call last):
  File "C:\Users\sivaprakashreddy\Desktop\micropython-1.9.2\py\makeqstrdata.py", line 158, in <module>
    do_work(sys.argv[1:])
  File "C:\Users\sivaprakashreddy\Desktop\micropython-1.9.2\py\makeqstrdata.py", line 155, in do_work
    print_qstr_data(qcfgs, qstrs)
  File "C:\Users\sivaprakashreddy\Desktop\micropython-1.9.2\py\makeqstrdata.py", line 138, in print_qstr_data
    cfg_bytes_len = int(qcfgs['BYTES_IN_LEN'])
ValueError: invalid literal for int() with base 10: 'MICROPY_QSTR_BYTES_IN_LEN'

C:\Users\sivaprakashreddy\Desktop\micropython-1.9.2\py>

Please help me in this regard.

Thanks and Regards,
Siva Prakash Reddy

**Comment by SUBBU3881** [comment]
can anyone respond please.?

**Comment by dpgeorge** [comment]
You can't process qstrdefs.h directly with makeqstrdata.py.  You first need to run qstrdefs.h through the C preprocessor to substitute the symbols (eg MICROPY_QSTR_BYTES_IN_LEN) with their values.

**Comment by psalm842** [comment]
@SUBBU3881, are you still working on this? Any notable progress? I am interested in building for the Tricore architecture as well.
