### ISSUE TITLE
MicroPython as a Package for Unix

### ISSUE THREAD

**Issue by SUBBU3881** [micropython/micropython-infineon#4]
Hi,
     To understand the micropython building procedure, I choose "/unix" and I built it successfully and bin file got generated. Now, I want to ad as a package instead of binary image. So suggest a procedure to install as a package in Linux PC.

Thanks and Regards,
Siva Prakash Reddy

**Comment by SUBBU3881** [comment]
@dpgeorge Please respond Sir

**Comment by dpgeorge** [comment]
> So suggest a procedure to install as a package in Linux PC.

This will depend on the Linux distribution that you are targeting (eg Ubuntu).  You will need to read the documentation for that distribution to see how to create a new package and install it.
